# © 2021 Carlos R. Silveira, Manoel dos Santos, ATSti Solucoes
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).

from odoo import api, fields, models, _
from datetime import datetime, timedelta

class Obito(models.Model):
    _name = "obito" 
    _description = "Obituario"
    _order = 'data_sistema desc, id desc'

    name = fields.Char('Obito', size=128)
    tipo_obito = fields.Selection([('S','Socio'),('P','Particular'),('O','Outros')], 'Tipo de Obito')
    data_sistema = fields.Date('Data Inclusão') 
    cor = fields.Char('Cor', size=50)
    data_nasc = fields.Date('Data Nasc.')
    falecido = fields.Many2one('res.partner', 'Socio / Dependente')
    #task_id = fields.Many2one('project.task', 'Project Task', required=True, ondelete="cascade", select=True, auto_join=True)
    profissao = fields.Char(u'Profissão', size=128)
    naturalidade = fields.Char('Natural', size=100)
    cpf_falecido = fields.Char('CPF', size=15)
    rg_falecido = fields.Char('RG / RNE ', size=20)
    ssp_falecido = fields.Char('Orgão', size=15)
    dta_expedicao = fields.Date('Data Exp.')
    nacionalidade = fields.Char('Nacionalidade', size=100)
    local_nascimento =  fields.Char('Local Nascimento', size=100)
    country_id = fields.Many2one('res.country', string='Pais', ondelete='restrict')
    cidade_eleitoral = fields.Many2one(
        'res.state.city', u'Cidade Eleitoral')
    zona = fields.Char('Zona Eleitoral', size=50)
    secao = fields.Char('Seção', size=40)
    num = fields.Char('Nº', size=20)
    end_falecido = fields.Char('Endereço', size=100)
    num_falecido = fields.Char('Nº', size=10)
    bairro = fields.Char('Bairro', size=100)
    state_id = fields.Many2one(
        'res.country.state', string="UF", required=True)
    cidade = fields.Many2one(
        'res.state.city', u'Cidade')
    country_id = fields.Many2one('res.country', string='Pais', ondelete='restrict')
    deixa_bens = fields.Selection([('S','Sim'),('N','Não'),('I','Ignorado')], 'Deixa Bens')
    testamento = fields.Selection([('S','Sim'),('N','Não'),('I','Ignorado')], 'Testamento')
    inss = fields.Selection([('S','Sim'),('N','Não'),('I','Ignorado')], 'INSS')
    num_beneficio = fields.Char('Nº', size=40)        
    csm = fields.Char(u'CSM', size=128)
    rm = fields.Char(u'RM', size=128)
    reservista = fields.Char(u'Reservista', size=128)
    categoria = fields.Char('Categoria', size=30)
    num_reservista =  fields.Char('Nº', size=30)
    serie = fields.Char('Serie', size=20)
    docs_apresentado = fields.Text('Docs. Apresentado')
    falecido_mae = fields.Char(u'Mãe', size=128)
    falecido_pai = fields.Char(u'Pai', size=128)
    sexo = fields.Selection([('F', 'Feminino'),('M', 'Masculino')], 'Sexo')
    estado_civil = fields.Selection([('C','Casado'),('S','Solteiro'),('D','Divorciado')], 'Estado Civil')
    
    e_eleitor = fields.Selection([('S','Sim'),('N','Não'),('I','Ignorado')], 'É eleitor ?')
    falecido_maes = fields.Char(u'Mãe', size=128)
       
        
    # Aba Dados Falecimento
    cemiterio = fields.Char('Cemiterio', size=100)
    hora_sep = fields.Float('Hora Sepultamento')
    data_sep = fields.Date('Data Sepultamento')
    local_fal = fields.Char('Local Falecimento', size=100)
    hora_fal =  fields.Float('Hora Falecimento')
    data_fal = fields.Date('Data Falecimento')  
    crm1 = fields.Char('CRM', size=50)
    crm2 =  fields.Char('CRM', size=50)
    causa_morte = fields.Char('Causa Morte', size=300)
    obs = fields.Char('Obs:', size=200)
    conjuge1 = fields.Char('Conjuge', size=100)
    conj_data1 = fields.Date('Data Cas.') 
    conj_nupcias1 = fields.Char('Nupcias', size=100)
    conj_livro1 = fields.Char('Livro', size=40)
    conj_folha1 = fields.Char('Folha', size=20)        
    conj_num1 = fields.Char('Nº', size=20)
    conjuge2 = fields.Char('Conjuge', size=100)
    conj_data2 = fields.Date('Data Cas.') 
    conj_nupcias2 = fields.Char('Nupcias', size=100)
    conj_livro2 = fields.Char('Livro', size=40)
    conj_folha2 = fields.Char('Folha', size=20)        
    conj_num2 = fields.Char('Nº', size=20)        
        
    # aba Dados dos Pais
    nome_pai = fields.Char('Pai', size=100)
    natural_pai = fields.Char('Natural de', size=100)
    nome_mae = fields.Char('Mãe', size=100)
    natural_mae =  fields.Char('Natural de', size=100)          
    estcivil_pai = fields.Char('Est Civil', size=100)
    d_nasc_pai = fields.Date('Data Nasc Pai') 
    profissiao_pai = fields.Char('Profissão Pai', size=100)
    Falecido_mae = fields.Char('Mão Falecido', size=100)
    falecido_pai = fields.Char('Pai Falecido', size=100)
    falecido_maes = fields.Char('Prcisa ver o que é', size=100)
    estcivil_mae = fields.Char('Est. Civi Mãe', size=100)
    d_nasc_mae = fields.Date('Data Nasc Mãe')
    profissiao_mae = fields.Char('Profissão Mãe', size=100)
    endereco_pais = fields.Char('Endereço Pais', size=100)
    numero_pais = fields.Char('Nº', size=5)
    bairro_pais = fields.Char('Bairro', size=40)
    cidade_pais = fields.Char('Cidade', size=40)
    cidade_pais = fields.Many2one(
        'res.state.city', u'Cidade')
    uf_pais = fields.Many2one("res.country.state", string='UF', ondelete='restrict', domain="[('country_id', '=?', country_id)]")
    cep_pais = fields.Char('CEP', size=15)
    nupcias_pais = fields.Char('Nupcias', size=100)
    data_casamento_pai = fields.Date('Data Casasamento') 
    livro_pai = fields.Char('Livro', size=20)
    folha_pai = fields.Char('Folha', size=10)
    num_pai = fields.Char('Nº', size=10)
    avos_paterno1 = fields.Char('Avos Paterno', size=100)
    avos_paterno2 = fields.Char('Avos Paterno', size=100)
    avos_materno1 = fields.Char('Avos Materno', size=100)
    avos_materno2 = fields.Char('Avos Materno', size=100)
        
    # aba Filhos   Precisar corrigir o campo Idade
    nome_filho = fields.Char('Filho' , size=100)
    idade_filho = fields.Char('Idade' , size=3)

    # aba declarante
    declarante = fields.Char('Declarante', size=80)
    decla_nacionalidade = fields.Char('Nacionalidade', size=30)
    cpf_declarante = fields.Char('CPF', size=15)
    rg_cpf = fields.Char('RG RNE', size=20) 
    ssp_declarante = fields.Char('SSP', size=30) 
    grau_parentesco = fields.Char('Grau Parentesco ', size=30) 
    fone_decl = fields.Char('Fone', size=30) 
    profissiao_decl = fields.Char('Profissão', size=50) 
    decla_estcivil = fields.Char('Estado Civil', size=50)
    endereco_decl = fields.Char('Endereço', size=100) 
    velorio = fields.Char('Velorio', size=200) 
    registro_cartorio = fields.Char('Registro', size=100)
    endereco_cartorio = fields.Char('Endereço', size=100)
    cidade_cartorio = fields.Char('Cidade', size=100)
